name: class_box
description: ClassBox for Study.

publish_to: 'none'

version: 0.5.1+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.17.1
  firebase_auth: ^3.3.18
  google_sign_in: ^5.3.2
  google_fonts: ^3.0.1
  material_design_icons_flutter: ^5.0.6595
  blurrycontainer: ^1.0.2
  flutter_facebook_auth: ^4.3.4
  cloud_firestore: ^3.1.17
  flutter_staggered_grid_view: ^0.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/auth_bg.png
    - assets/images/home_bg.png