// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiQrPlMk2nC-NgC-2xuqlbQYxO__uZ4Kk',
    appId: '1:68631060885:web:9e6fd140bf6fe6e18d569c',
    messagingSenderId: '68631060885',
    projectId: 'class-box-011',
    authDomain: 'class-box-011.firebaseapp.com',
    storageBucket: 'class-box-011.appspot.com',
    measurementId: 'G-HMK743H0TC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVqlO75mBh3lJQ4oXJrf3mrOo8AvtSek8',
    appId: '1:68631060885:android:d0fdd93f3fcb1a548d569c',
    messagingSenderId: '68631060885',
    projectId: 'class-box-011',
    storageBucket: 'class-box-011.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9pOwgq2xFrHp2G-fzZv2EqaH1jTVnjbg',
    appId: '1:68631060885:ios:c61f59a7628dc6f58d569c',
    messagingSenderId: '68631060885',
    projectId: 'class-box-011',
    storageBucket: 'class-box-011.appspot.com',
    iosClientId: '68631060885-pmn81sua14j4o0nmampmd6hippk1klpu.apps.googleusercontent.com',
    iosBundleId: 'com.example.classBox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9pOwgq2xFrHp2G-fzZv2EqaH1jTVnjbg',
    appId: '1:68631060885:ios:c61f59a7628dc6f58d569c',
    messagingSenderId: '68631060885',
    projectId: 'class-box-011',
    storageBucket: 'class-box-011.appspot.com',
    iosClientId: '68631060885-pmn81sua14j4o0nmampmd6hippk1klpu.apps.googleusercontent.com',
    iosBundleId: 'com.example.classBox',
  );
}
